default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  timeout: 5000

development:
  <<: *default
  database: luxury_db
  
test:
  <<: *default
  database: luxury_db

production:
  primary: &primary_production
    <<: *default
    database: luxury_db
    username: luxury_app
    password: <%= ENV["BLOG_TEST_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: luxury_db_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: luxury_db_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: luxury_db_production_cable
    migrations_paths: db/cable_migrate
